### ISSUE TITLE
Random changes in b_p when adjusting a_CDOM

### ISSUE THREAD

**Issue by yulunwu8** [bishun945/IOPmodel#2]
Hi Shun,

I’ve been exploring your tool - it’s very impressive and useful! 

Please see attached screenshots - I adjusted a_CDOM from 10.1 to 10.8 in increments of 0.1, and it seems to introduce random changes in b_p. Do you know what was happening? 

Cheers,
Yulun
[screenshots.zip](https://github.com/user-attachments/files/17789388/screenshots.zip)

**Comment by bishun945** [comment]
Hi Yulun,

thanks for spotting this bug!

The issue arises due to certain "Model Parameter" settings in the "Settings" panel, specifically the Detritus single scattering albedo (A_d) and the Power law exponent for detritus attenuation (G_d).

Our IOP model (@martinhiero) calculates scattering by subtracting absorption from attenuation (Bi et al., 2023), which can sometimes result in negative scattering values at wavelengths other than the reference (550 nm). In cases where G_d is set to zero, as in your screenshot, the c_d spectrum is flat. However, if the slopes for a_d (based on two quantile values), Chl, or ISM are too steep, this subtraction can lead to negative values for c_d - a_d at shorter wavelengths. The code detects such inconsistencies and automatically regenerates more appropriate values for G_d, A_d, and the two quantiles, referencing the statistical values from the paper. This is why these parameters were moved to the "Settings" panel, as they are often secondary.

I've now updated the R code to better handle these warnings. It will alert users when improper parameters are set, and the regenerated parameters will update automatically. After that, you can return to the first panel to adjust other values, such as a_CDOM, and run the model as needed.

I hope this resolves your issue! Let me know if you have further questions.

Check the update web app in the same link [here](https://bishun945.shinyapps.io/IOPmodel/).

Best regards,
Shun

**Comment by yulunwu8** [comment]
This is clear, thanks a lot for answering!!

Best regards,
Yulun
